
{******************************************}
{                                          }
{             FastReport v4.0              }
{              Include file                }
{                                          }
{    (c) 2011 by Alexander Tzyganenko,     }
{             Fast Reports, Inc            }
{                                          }
{******************************************}

{$DEFINE FMX}
