// CodeGear C++Builder
// Copyright (c) 1995, 2015 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'FMXfrxTee23.dpk' rev: 30.00 (MacOS)

#ifndef Fmxfrxtee23HPP
#define Fmxfrxtee23HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FMX.frxChart.hpp>
#include <FMX.frxChartEditor.hpp>
#include <FMX.frxChartGallery.hpp>
#include <FMX.frxChartHelpers.hpp>
#include <FMX.frxChartRTTI.hpp>
#include <System.Types.hpp>	// (rtl)
#include <Posix.Base.hpp>	// (rtl)
#include <Posix.Dlfcn.hpp>	// (rtl)
#include <Posix.StdDef.hpp>	// (rtl)
#include <Posix.SysTypes.hpp>	// (rtl)
#include <Posix.Fcntl.hpp>	// (rtl)
#include <Posix.SysStat.hpp>	// (rtl)
#include <Posix.Signal.hpp>	// (rtl)
#include <Posix.Time.hpp>	// (rtl)
#include <Posix.SysTime.hpp>	// (rtl)
#include <System.Internal.Unwinder.hpp>	// (rtl)
#include <Macapi.Mach.hpp>	// (rtl)
#include <Macapi.CoreServices.hpp>	// (rtl)
#include <Macapi.CoreFoundation.hpp>	// (rtl)
#include <System.SysConst.hpp>	// (rtl)
#include <Posix.Iconv.hpp>	// (rtl)
#include <Posix.Dirent.hpp>	// (rtl)
#include <Posix.Errno.hpp>	// (rtl)
#include <Posix.Fnmatch.hpp>	// (rtl)
#include <Posix.Locale.hpp>	// (rtl)
#include <Posix.Langinfo.hpp>	// (rtl)
#include <Posix.Sched.hpp>	// (rtl)
#include <Posix.Pthread.hpp>	// (rtl)
#include <Posix.Stdio.hpp>	// (rtl)
#include <Posix.Stdlib.hpp>	// (rtl)
#include <Posix.String_.hpp>	// (rtl)
#include <Posix.SysSysctl.hpp>	// (rtl)
#include <Posix.Unistd.hpp>	// (rtl)
#include <Posix.Utime.hpp>	// (rtl)
#include <Posix.Wordexp.hpp>	// (rtl)
#include <Posix.Pwd.hpp>	// (rtl)
#include <Posix.SysUio.hpp>	// (rtl)
#include <Posix.SysSocket.hpp>	// (rtl)
#include <Posix.ArpaInet.hpp>	// (rtl)
#include <Posix.NetinetIn.hpp>	// (rtl)
#include <System.RTLConsts.hpp>	// (rtl)
#include <Posix.Wchar.hpp>	// (rtl)
#include <Posix.Wctype.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.MachExceptions.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.StrUtils.hpp>	// (rtl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Hash.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Generics.Collections.hpp>	// (rtl)
#include <Posix.SysMman.hpp>	// (rtl)
#include <System.Internal.Unwind.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <Posix.StrOpts.hpp>	// (rtl)
#include <Posix.SysSelect.hpp>	// (rtl)
#include <Macapi.ObjCRuntime.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.UITypes.hpp>	// (rtl)
#include <System.Math.Vectors.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <System.ImageList.hpp>	// (rtl)
#include <FMX.Consts.hpp>	// (fmx)
#include <Macapi.CocoaTypes.hpp>	// (rtl)
#include <Macapi.OCMarshal.hpp>	// (rtl)
#include <Macapi.Consts.hpp>	// (rtl)
#include <Macapi.OCBlocks.hpp>	// (rtl)
#include <Macapi.ObjectiveC.hpp>	// (rtl)
#include <Macapi.Foundation.hpp>	// (rtl)
#include <Macapi.QuartzCore.hpp>	// (rtl)
#include <Macapi.AppKit.hpp>	// (rtl)
#include <System.Mac.Devices.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <System.Analytics.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <FMX.Surfaces.hpp>	// (fmx)
#include <System.RegularExpressionsAPI.hpp>	// (rtl)
#include <System.RegularExpressionsConsts.hpp>	// (rtl)
#include <System.RegularExpressionsCore.hpp>	// (rtl)
#include <System.RegularExpressions.hpp>	// (rtl)
#include <FMX.Text.hpp>	// (fmx)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.hpp>	// (fmx)
#include <FMX.Materials.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <System.Masks.hpp>	// (rtl)
#include <Macapi.Helpers.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Mac.CFUtils.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <FMX.Objects.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <FMX.Gestures.Mac.hpp>	// (fmx)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.ImgList.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <Macapi.CoreGraphics.hpp>	// (rtl)
#include <Macapi.CoreText.hpp>	// (rtl)
#include <FMX.FontGlyphs.Mac.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.Materials.Canvas.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.StrokeBuilder.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.StdActns.hpp>	// (fmx)
#include <FMX.Presentation.Messages.hpp>	// (fmx)
#include <FMX.Controls.Model.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.Presentation.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <Posix.Semaphore.hpp>	// (rtl)
#include <System.Diagnostics.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <Macapi.KeyCodes.hpp>	// (rtl)
#include <Macapi.ImageIO.hpp>	// (rtl)
#include <FMX.Printer.Mac.hpp>	// (fmx)
#include <FMX.Printer.hpp>	// (fmx)
#include <FMX.Canvas.Mac.hpp>	// (fmx)
#include <Macapi.OpenGL.hpp>	// (rtl)
#include <FMX.Context.Mac.hpp>	// (fmx)
#include <FMX.KeyMapping.hpp>	// (fmx)
#include <FMX.ListBox.Selection.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.Calendar.Style.hpp>	// (fmx)
#include <FMX.Calendar.hpp>	// (fmx)
#include <FMX.Pickers.Default.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <FMX.Controls.Mac.hpp>	// (fmx)
#include <FMX.Forms.Border.hpp>	// (fmx)
#include <FMX.Forms.Border.Mac.hpp>	// (fmx)
#include <FMX.Helpers.Mac.hpp>	// (fmx)
#include <FMX.Platform.Mac.hpp>	// (fmx)
#include <FMX.Platform.Common.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.ActnList.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <System.WideStrUtils.hpp>	// (rtl)
#include <System.WideStrings.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <FMX.frxXML.hpp>	// (FMXfrx23)
#include <FMX.TreeView.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.SpellChecker.Mac.hpp>	// (fmx)
#include <FMX.SpellChecker.hpp>	// (fmx)
#include <FMX.Edit.Style.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.frxFMX.hpp>	// (FMXfrx23)
#include <FMX.frxUnicodeUtils.hpp>	// (FMXfrx23)
#include <FMX.fs_iconst.hpp>	// (FMXfs23)
#include <System.ZLib.hpp>	// (rtl)
#include <FMX.frxGZip.hpp>	// (FMXfrx23)
#include <FMX.frxRes.hpp>	// (FMXfrx23)
#include <FMX.frxUtils.hpp>	// (FMXfrx23)
#include <FMX.frxXMLSerializer.hpp>	// (FMXfrx23)
#include <FMX.frxVariables.hpp>	// (FMXfrx23)
#include <FMX.frxProgress.hpp>	// (FMXfrx23)
#include <FMX.fs_xml.hpp>	// (FMXfs23)
#include <FMX.fs_iparser.hpp>	// (FMXfs23)
#include <FMX.fs_itools.hpp>	// (FMXfs23)
#include <System.MaskUtils.hpp>	// (rtl)
#include <FMX.fs_isysrtti.hpp>	// (FMXfs23)
#include <FMX.fs_iexpression.hpp>	// (FMXfs23)
#include <FMX.fs_iilparser.hpp>	// (FMXfs23)
#include <FMX.fs_iinterpreter.hpp>	// (FMXfs23)
#include <FMX.frxAggregate.hpp>	// (FMXfrx23)
#include <FMX.Colors.hpp>	// (fmx)
#include <FMX.frxFontForm.hpp>	// (FMXfrx23)
#include <FMX.frxDsgnIntf.hpp>	// (FMXfrx23)
#include <FMX.frxDMPClass.hpp>	// (FMXfrx23)
#include <FMX.frxPictureCache.hpp>	// (FMXfrx23)
#include <FMX.frxCtrls.hpp>	// (FMXfrx23)
#include <FMX.ComboEdit.Style.hpp>	// (fmx)
#include <FMX.ComboEdit.hpp>	// (fmx)
#include <FMX.Mac.frxPrinter.hpp>	// (FMXfrx23)
#include <FMX.frxPrinter.hpp>	// (FMXfrx23)
#include <FMX.frxSearchDialog.hpp>	// (FMXfrx23)
#include <FMX.frxPreviewPageSettings.hpp>	// (FMXfrx23)
#include <FMX.frxPreview.hpp>	// (FMXfrx23)
#include <FMX.frxPrintDialog.hpp>	// (FMXfrx23)
#include <FMX.frxPreviewPages.hpp>	// (FMXfrx23)
#include <FMX.frxEngine.hpp>	// (FMXfrx23)
#include <FMX.frxPassw.hpp>	// (FMXfrx23)
#include <FMX.frxDialogForm.hpp>	// (FMXfrx23)
#include <FMX.frxGraphicUtils.hpp>	// (FMXfrx23)
#include <FMX.frxrcClass.hpp>	// (FMXfrx23)
#include <FMX.fs_iclassesrtti.hpp>	// (FMXfs23)
#include <FMX.fs_ievents.hpp>	// (FMXfs23)
#include <FMX.fs_igraphicsrtti.hpp>	// (FMXfs23)
#include <FMX.Memo.Types.hpp>	// (fmx)
#include <FMX.ScrollBox.Style.hpp>	// (fmx)
#include <FMX.ScrollBox.hpp>	// (fmx)
#include <FMX.Memo.Style.hpp>	// (fmx)
#include <FMX.Memo.hpp>	// (fmx)
#include <FMX.fs_iformsrtti.hpp>	// (FMXfs23)
#include <FMX.frxClassRTTI.hpp>	// (FMXfrx23)
#include <FMX.frxInheritError.hpp>	// (FMXfrx23)
#include <FMX.fs_ipascal.hpp>	// (FMXfs23)
#include <FMX.fs_icpp.hpp>	// (FMXfs23)
#include <FMX.fs_ibasic.hpp>	// (FMXfs23)
#include <FMX.fs_ijs.hpp>	// (FMXfs23)
#include <FMX.fs_idialogsrtti.hpp>	// (FMXfs23)
#include <FMX.fs_iinirtti.hpp>	// (FMXfs23)
#include <FMX.frxClass.hpp>	// (FMXfrx23)
#include <FMXTee.Html.hpp>	// (FMXTee)
#include <FMXTee.Constants.hpp>	// (FMXTee)
#include <FMXTee.Canvas.hpp>	// (FMXTee)
#include <FMXTee.Procs.hpp>	// (FMXTee)
#include <FMXTee.Engine.hpp>	// (FMXTee)
#include <FMXTee.Chart.hpp>	// (FMXTee)
#include <FMXTee.Series.hpp>	// (FMXTee)
#include <FMX.fs_ichartrtti.hpp>	// (FMXfsTee23)
#include <Macapi.JavaScriptCore.hpp>	// (rtl)
#include <Macapi.WebKit.hpp>	// (rtl)
#include <FMX.WebBrowser.Delegate.Mac.hpp>	// (fmx)
#include <FMX.WebBrowser.Cocoa.hpp>	// (fmx)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.TabControl.hpp>	// (fmx)
#include <FMX.frxEditFormat.hpp>	// (FMXfrx23)
#include <FMX.frxEditHighlight.hpp>	// (FMXfrx23)
#include <FMX.frxEditSysMemo.hpp>	// (FMXfrx23)
#include <FMX.frxEditMemo.hpp>	// (FMXfrx23)
#include <FMX.frxCustomEditors.hpp>	// (FMXfrx23)
#include <FMX.frxrcInsp.hpp>	// (FMXfrx23)
#include <FMX.frxInsp.hpp>	// (FMXfrx23)
#include <FMXTee.Chart.GalleryPanel.hpp>	// (FmxTeeUI)

//-- user supplied -----------------------------------------------------------

namespace Fmxfrxtee23
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Fmxfrxtee23 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_FMXFRXTEE23)
using namespace Fmxfrxtee23;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Fmxfrxtee23HPP
