// CodeGear C++Builder
// Copyright (c) 1995, 2015 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'FMXfrxADO23.dpk' rev: 30.00 (Windows)

#ifndef Fmxfrxado23HPP
#define Fmxfrxado23HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FMX.frxADOComponents.hpp>
#include <FMX.frxADOEditor.hpp>
#include <FMX.frxADORTTI.hpp>
#include <Winapi.Windows.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <FMX.Objects.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <FMX.ImgList.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <FMX.Helpers.Win.hpp>	// (fmx)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <FMX.Canvas.GDIP.hpp>	// (fmx)
#include <FMX.Printer.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.Controls.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.Switch.Win.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.Edit.Style.hpp>	// (fmx)
#include <FMX.Edit.Win.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.Dialogs.Win.hpp>	// (fmx)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <FMX.Canvas.D2D.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.Context.DX9.hpp>	// (fmx)
#include <FMX.Context.DX11.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.Calendar.Style.hpp>	// (fmx)
#include <FMX.Calendar.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <System.Win.InternetExplorer.hpp>	// (rtl)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.Platform.Win.hpp>	// (fmx)
#include <FMX.Gestures.Win.hpp>	// (fmx)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.TreeView.hpp>	// (fmx)
#include <FMX.frxFMX.hpp>	// (FMXfrx23)
#include <FMX.fs_iconst.hpp>	// (FMXfs23)
#include <FMX.frxRes.hpp>	// (FMXfrx23)
#include <FMX.fs_itools.hpp>	// (FMXfs23)
#include <FMX.fs_iinterpreter.hpp>	// (FMXfs23)
#include <FMX.Colors.hpp>	// (fmx)
#include <FMX.frxDsgnIntf.hpp>	// (FMXfrx23)
#include <FMX.frxDMPClass.hpp>	// (FMXfrx23)
#include <FMX.frxCtrls.hpp>	// (FMXfrx23)
#include <FMX.ComboEdit.Style.hpp>	// (fmx)
#include <FMX.ComboEdit.hpp>	// (fmx)
#include <FMX.Win.frxPrinter.hpp>	// (FMXfrx23)
#include <FMX.frxPrinter.hpp>	// (FMXfrx23)
#include <FMX.frxSearchDialog.hpp>	// (FMXfrx23)
#include <FMX.frxPreview.hpp>	// (FMXfrx23)
#include <FMX.frxrcClass.hpp>	// (FMXfrx23)
#include <FMX.fs_iclassesrtti.hpp>	// (FMXfs23)
#include <FMX.fs_igraphicsrtti.hpp>	// (FMXfs23)
#include <FMX.ScrollBox.Style.hpp>	// (fmx)
#include <FMX.ScrollBox.Win.hpp>	// (fmx)
#include <FMX.ScrollBox.hpp>	// (fmx)
#include <FMX.Memo.Style.hpp>	// (fmx)
#include <FMX.Memo.Win.hpp>	// (fmx)
#include <FMX.Memo.hpp>	// (fmx)
#include <FMX.fs_iformsrtti.hpp>	// (FMXfs23)
#include <FMX.frxClassRTTI.hpp>	// (FMXfrx23)
#include <FMX.fs_ipascal.hpp>	// (FMXfs23)
#include <FMX.fs_icpp.hpp>	// (FMXfs23)
#include <FMX.fs_ibasic.hpp>	// (FMXfs23)
#include <FMX.fs_ijs.hpp>	// (FMXfs23)
#include <FMX.fs_idialogsrtti.hpp>	// (FMXfs23)
#include <FMX.fs_iinirtti.hpp>	// (FMXfs23)
#include <FMX.frxClass.hpp>	// (FMXfrx23)
#include <Data.SqlTimSt.hpp>	// (dbrtl)
#include <Data.FmtBcd.hpp>	// (dbrtl)
#include <Data.DB.hpp>	// (dbrtl)
#include <FMX.Grid.hpp>	// (fmx)
#include <FMX.fs_synmemo.hpp>	// (FMXfs23)
#include <FMX.TabControl.hpp>	// (fmx)
#include <FMX.frxConnWizard.hpp>	// (FMXfrxDB23)
#include <FMX.frxCustomDBEditor.hpp>	// (FMXfrxDB23)
#include <FMX.fs_idbrtti.hpp>	// (FMXfsDB23)
#include <FMX.frxCustomDBRTTI.hpp>	// (FMXfrxDB23)
#include <FMX.frxCustomDB.hpp>	// (FMXfrxDB23)
#include <Data.Win.ADODB.hpp>	// (adortl)
#include <FMX.fs_iadortti.hpp>	// (FMXfsADO23)

//-- user supplied -----------------------------------------------------------

namespace Fmxfrxado23
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Fmxfrxado23 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_FMXFRXADO23)
using namespace Fmxfrxado23;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Fmxfrxado23HPP
