// CodeGear C++Builder
// Copyright (c) 1995, 2015 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'FMXfrxe23.dpk' rev: 30.00 (Windows)

#ifndef Fmxfrxe23HPP
#define Fmxfrxe23HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FMX.frxExportHTML.hpp>
#include <FMX.frxExportImage.hpp>
#include <FMX.frxImageConverter.hpp>
#include <FMX.frxExportMatrix.hpp>
#include <FMX.frxExportRTF.hpp>
#include <FMX.frxExportText.hpp>
#include <FMX.frxExportXML.hpp>
#include <FMX.frxRC4.hpp>
#include <FMX.frxCmapTableClass.hpp>
#include <FMX.frxGlyphTableClass.hpp>
#include <FMX.frxGlyphSubstitutionClass.hpp>
#include <FMX.frxHorizontalHeaderClass.hpp>
#include <FMX.frxHorizontalMetrixClass.hpp>
#include <FMX.frxIndexToLocationClass.hpp>
#include <FMX.frxKerningTableClass.hpp>
#include <FMX.frxPostScriptClass.hpp>
#include <FMX.frxMaximumProfileClass.hpp>
#include <FMX.frxOS2WindowsMetricsClass.hpp>
#include <FMX.frxPreProgramClass.hpp>
#include <FMX.frxTrueTypeFont.hpp>
#include <FMX.frxFontHeaderClass.hpp>
#include <FMX.TTFHelpers.hpp>
#include <FMX.frxTrueTypeTable.hpp>
#include <FMX.frxNameTableClass.hpp>
#include <FMX.frxmd5.hpp>
#include <FMX.frxCrypto.hpp>
#include <FMX.frxTrueTypeCollection.hpp>
#include <FMX.frxExportPDF.hpp>
#include <FMX.frxExportCSV.hpp>
#include <FMX.frxrcExports.hpp>
#include <System.Types.hpp>	// (rtl)
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <System.SysConst.hpp>	// (rtl)
#include <Winapi.ImageHlp.hpp>	// (rtl)
#include <Winapi.SHFolder.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.RTLConsts.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <Winapi.Messages.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <Winapi.ActiveX.hpp>	// (rtl)
#include <System.StrUtils.hpp>	// (rtl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Hash.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Generics.Collections.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.Math.Vectors.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <System.ImageList.hpp>	// (rtl)
#include <FMX.Consts.hpp>	// (fmx)
#include <System.Win.Devices.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <System.Analytics.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <FMX.Surfaces.hpp>	// (fmx)
#include <System.Win.Crtl.hpp>	// (rtl)
#include <System.RegularExpressionsAPI.hpp>	// (rtl)
#include <System.RegularExpressionsConsts.hpp>	// (rtl)
#include <System.RegularExpressionsCore.hpp>	// (rtl)
#include <System.RegularExpressions.hpp>	// (rtl)
#include <FMX.Text.hpp>	// (fmx)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.hpp>	// (fmx)
#include <FMX.Materials.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <System.Masks.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <FMX.Objects.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <Winapi.TpcShrd.hpp>	// (rtl)
#include <Winapi.MsInkAut.hpp>	// (rtl)
#include <Winapi.Manipulations.hpp>	// (rtl)
#include <Winapi.RtsCom.hpp>	// (rtl)
#include <Winapi.CommCtrl.hpp>	// (rtl)
#include <FMX.ZOrder.Win.hpp>	// (fmx)
#include <Winapi.Qos.hpp>	// (rtl)
#include <Winapi.Winsock2.hpp>	// (rtl)
#include <Winapi.IpExport.hpp>	// (rtl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Winapi.RegStr.hpp>	// (rtl)
#include <Winapi.WinInet.hpp>	// (rtl)
#include <Winapi.UrlMon.hpp>	// (rtl)
#include <Winapi.ObjectArray.hpp>	// (rtl)
#include <Winapi.StructuredQueryCondition.hpp>	// (rtl)
#include <Winapi.PropSys.hpp>	// (rtl)
#include <Winapi.MSXMLIntf.hpp>	// (rtl)
#include <Winapi.ShlObj.hpp>	// (rtl)
#include <Winapi.CommDlg.hpp>	// (rtl)
#include <Winapi.MMSystem.hpp>	// (rtl)
#include <Winapi.MultiMon.hpp>	// (rtl)
#include <Winapi.Imm.hpp>	// (rtl)
#include <System.Diagnostics.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <FMX.ImgList.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <System.Win.ComConst.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <FMX.Helpers.Win.hpp>	// (fmx)
#include <Winapi.WinSpool.hpp>	// (rtl)
#include <Winapi.DirectDraw.hpp>	// (rtl)
#include <Winapi.GDIPAPI.hpp>	// (rtl)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <Winapi.GDIPUTIL.hpp>	// (rtl)
#include <FMX.Canvas.GDIP.hpp>	// (fmx)
#include <FMX.Printer.Win.hpp>	// (fmx)
#include <FMX.Printer.hpp>	// (fmx)
#include <FMX.StdActns.hpp>	// (fmx)
#include <FMX.Presentation.Messages.hpp>	// (fmx)
#include <FMX.Controls.Model.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.Presentation.Style.hpp>	// (fmx)
#include <FMX.Controls.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.Switch.Win.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.SpellChecker.hpp>	// (fmx)
#include <FMX.Edit.Style.hpp>	// (fmx)
#include <FMX.Edit.Win.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.Dialogs.Default.hpp>	// (fmx)
#include <FMX.Dialogs.Win.hpp>	// (fmx)
#include <Winapi.DXTypes.hpp>	// (rtl)
#include <Winapi.DxgiFormat.hpp>	// (rtl)
#include <Winapi.DxgiType.hpp>	// (rtl)
#include <Winapi.DXGI.hpp>	// (rtl)
#include <Winapi.D3D10.hpp>	// (rtl)
#include <Winapi.Wincodec.hpp>	// (rtl)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Winapi.D3DCommon.hpp>	// (rtl)
#include <Winapi.D3D10_1.hpp>	// (rtl)
#include <FMX.Canvas.D2D.hpp>	// (fmx)
#include <Winapi.Direct3D9.hpp>	// (rtl)
#include <FMX.Materials.Canvas.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.FontGlyphs.Win.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.StrokeBuilder.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.Context.DX9.hpp>	// (fmx)
#include <Winapi.D3D11.hpp>	// (rtl)
#include <FMX.Context.DX11.hpp>	// (fmx)
#include <FMX.Forms.Border.hpp>	// (fmx)
#include <FMX.ListBox.Selection.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.Calendar.Style.hpp>	// (fmx)
#include <FMX.Calendar.hpp>	// (fmx)
#include <FMX.Pickers.Default.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <FMX.Forms.Border.Win.hpp>	// (fmx)
#include <FMX.MultiTouch.hpp>	// (fmx)
#include <FMX.MultiTouch.Win.hpp>	// (fmx)
#include <System.Win.OleControls.hpp>	// (rtl)
#include <FMX.Controls.Ole.hpp>	// (fmx)
#include <System.Win.StdVCL.hpp>	// (rtl)
#include <System.Win.OleServers.hpp>	// (rtl)
#include <System.Win.InternetExplorer.hpp>	// (rtl)
#include <System.Win.IEInterfaces.hpp>	// (rtl)
#include <FMX.WebBrowser.Win.hpp>	// (fmx)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.Platform.Win.hpp>	// (fmx)
#include <FMX.Gestures.Win.hpp>	// (fmx)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <FMX.Platform.Common.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.ActnList.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <System.WideStrUtils.hpp>	// (rtl)
#include <System.WideStrings.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <FMX.frxXML.hpp>	// (FMXfrx23)
#include <FMX.TreeView.hpp>	// (fmx)
#include <FMX.frxFMX.hpp>	// (FMXfrx23)
#include <FMX.frxUnicodeUtils.hpp>	// (FMXfrx23)
#include <FMX.fs_iconst.hpp>	// (FMXfs23)
#include <System.ZLib.hpp>	// (rtl)
#include <FMX.frxGZip.hpp>	// (FMXfrx23)
#include <FMX.frxRes.hpp>	// (FMXfrx23)
#include <FMX.frxUtils.hpp>	// (FMXfrx23)
#include <FMX.frxXMLSerializer.hpp>	// (FMXfrx23)
#include <FMX.frxVariables.hpp>	// (FMXfrx23)
#include <FMX.frxProgress.hpp>	// (FMXfrx23)
#include <FMX.fs_xml.hpp>	// (FMXfs23)
#include <FMX.fs_iparser.hpp>	// (FMXfs23)
#include <FMX.fs_itools.hpp>	// (FMXfs23)
#include <System.MaskUtils.hpp>	// (rtl)
#include <FMX.fs_isysrtti.hpp>	// (FMXfs23)
#include <FMX.fs_iexpression.hpp>	// (FMXfs23)
#include <FMX.fs_iilparser.hpp>	// (FMXfs23)
#include <FMX.fs_iinterpreter.hpp>	// (FMXfs23)
#include <FMX.frxAggregate.hpp>	// (FMXfrx23)
#include <FMX.Colors.hpp>	// (fmx)
#include <FMX.frxFontForm.hpp>	// (FMXfrx23)
#include <FMX.frxDsgnIntf.hpp>	// (FMXfrx23)
#include <FMX.frxDMPClass.hpp>	// (FMXfrx23)
#include <FMX.frxPictureCache.hpp>	// (FMXfrx23)
#include <FMX.frxCtrls.hpp>	// (FMXfrx23)
#include <FMX.ComboEdit.Style.hpp>	// (fmx)
#include <FMX.ComboEdit.hpp>	// (fmx)
#include <FMX.Win.frxPrinter.hpp>	// (FMXfrx23)
#include <FMX.frxPrinter.hpp>	// (FMXfrx23)
#include <FMX.frxSearchDialog.hpp>	// (FMXfrx23)
#include <FMX.frxPreviewPageSettings.hpp>	// (FMXfrx23)
#include <FMX.frxPreview.hpp>	// (FMXfrx23)
#include <FMX.frxPrintDialog.hpp>	// (FMXfrx23)
#include <FMX.frxPreviewPages.hpp>	// (FMXfrx23)
#include <FMX.frxEngine.hpp>	// (FMXfrx23)
#include <FMX.frxPassw.hpp>	// (FMXfrx23)
#include <FMX.frxDialogForm.hpp>	// (FMXfrx23)
#include <FMX.frxGraphicUtils.hpp>	// (FMXfrx23)
#include <FMX.frxrcClass.hpp>	// (FMXfrx23)
#include <FMX.fs_iclassesrtti.hpp>	// (FMXfs23)
#include <FMX.fs_ievents.hpp>	// (FMXfs23)
#include <FMX.fs_igraphicsrtti.hpp>	// (FMXfs23)
#include <FMX.Memo.Types.hpp>	// (fmx)
#include <FMX.ScrollBox.Style.hpp>	// (fmx)
#include <FMX.ScrollBox.Win.hpp>	// (fmx)
#include <FMX.ScrollBox.hpp>	// (fmx)
#include <FMX.Memo.Style.hpp>	// (fmx)
#include <FMX.Memo.Win.hpp>	// (fmx)
#include <FMX.Memo.hpp>	// (fmx)
#include <FMX.fs_iformsrtti.hpp>	// (FMXfs23)
#include <FMX.frxClassRTTI.hpp>	// (FMXfrx23)
#include <FMX.frxInheritError.hpp>	// (FMXfrx23)
#include <FMX.fs_ipascal.hpp>	// (FMXfs23)
#include <FMX.fs_icpp.hpp>	// (FMXfs23)
#include <FMX.fs_ibasic.hpp>	// (FMXfs23)
#include <FMX.fs_ijs.hpp>	// (FMXfs23)
#include <FMX.fs_idialogsrtti.hpp>	// (FMXfs23)
#include <FMX.fs_iinirtti.hpp>	// (FMXfs23)
#include <FMX.frxClass.hpp>	// (FMXfrx23)
#include <FMX.TabControl.hpp>	// (fmx)
#include <FMX.frxChBoxRTTI.hpp>	// (FMXfrx23)
#include <FMX.frxChBox.hpp>	// (FMXfrx23)

//-- user supplied -----------------------------------------------------------

namespace Fmxfrxe23
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Fmxfrxe23 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_FMXFRXE23)
using namespace Fmxfrxe23;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Fmxfrxe23HPP
